<?php

/**
 * @file
 * Contains wbx_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function wbx_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wbx_slider module.
    case 'help.page.wbx_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides slider for front page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wbx_slider_theme() {
  return [
    'slide' => [
      'render element' => 'elements',
    ],
  ];
}

function template_preprocess_slide(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['slide'] = $variables['elements']['#slide'];
  $variables['url'] = Url::fromUri($variables['elements']['#slide']->get('field_link')->uri)->toString();

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

}