<?php

/**
 * @file
 * Contains wbx_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wbx_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wbx_slider module.
    case 'help.page.wbx_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides slider for front page') . '</p>';
      return $output;

    default:
  }
}
